### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by benjyz** [ericsomdahl/python-bittrex#17]
running tests I get an SSL error. Support told me "Please make sure you are disabling all ECDHE ciphers as they will lead to this error.". Didn't find any EC in the code, so no idea how to fix.

```
Traceback (most recent call last):
  File "/Users/ben/trading/python-bittrex/bittrex/test/bittrex_tests.py", line 31, in test_handles_none_key_or_secret
    actual = self.bittrex.get_markets()
  File "/Users/ben/trading/python-bittrex/bittrex/bittrex.py", line 78, in get_markets
    return self.api_query('getmarkets')
  File "/Users/ben/trading/python-bittrex/bittrex/bittrex.py", line 67, in api_query
    headers={"apisign": hmac.new(self.api_secret.encode(), request_url.encode(), hashlib.sha512).hexdigest()}
  File "/Library/Python/2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)


```

**Comment by ericsomdahl** [comment]
What platform and what version of Python are you running on?

I cannot reproduce this issue on either OSX or Linux, using 2.7.13

**Comment by sbres** [comment]
I had the same error. I installed pyopenssl, pyasn1 and ndg-httpsclient. And now it works.

`pip install -U pyopenssl pyasn1 ndg-httpsclient`
