### ISSUE TITLE
secrets.json present but "No json object could be decoded

### ISSUE THREAD

**Issue by Munkeynutz** [ericsomdahl/python-bittrex#33]
EE...
======================================================================
ERROR: test_get_balance (__main__.TestBittrexAccountAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bittrex_tests.py", line 67, in setUp
    self.secrets = json.load(secrets_file)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

======================================================================
ERROR: test_handles_invalid_key_or_secret (__main__.TestBittrexAccountAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bittrex_tests.py", line 67, in setUp
    self.secrets = json.load(secrets_file)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda2\envs\py2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

----------------------------------------------------------------------
Ran 5 tests in 0.953s

FAILED (errors=2)

JSON file is present, setup ran fine.
running in a python 2.7 envelope.
tried in a py3 envelope and same error.
.JSON file was made in Spyder....running Anaconda on windows.

**Comment by udayrddy** [comment]
Looks like you misplaced the **secrets**.json file or wrongly spelt. Please check to verify the file name is secret**s**.json (not secret) and placed in the **bittrex/test/** folder

**Comment by Munkeynutz** [comment]
![json](https://user-images.githubusercontent.com/30272708/28647024-b48d7416-7232-11e7-8d91-fdd3714d039a.jpg)

Pretty sure i got it right.

**Comment by Munkeynutz** [comment]
Not exactly sure why but I found a work around.
I had to change 
from bittrex.bittrex import Bittrex
to
from bittrex import Bittrex
after moving test.py to same directory.
Maybe some sort of PATH issue with Windows?  I have programdata\anaconda\scripts on path so not sure.

**Comment by ericsomdahl** [comment]
@Munkeynutz I don't have a Windows python environment to test this out on.  If you ever figure out what actually happened feel free to issue a PR :)
